 -- 11. Calculate the total revenue generated across all sales.
 
select sum(Revenue) as TotalRevenue from sales;

-- 12 .find the average revenue per sale.
select avg(Revenue)as avg_revenue from sales;


-- 13 Count the number of sales for each product.
select ProductID,sum(Quantity) as count_sales from sales s 
group by ProductID ;  

-- 14. Calculate the total quantity sold for each product.
select ProductID ,sum(Quantity) as total_quantity_sold 
from sales 
group by ProductID;

-- 15 Find the maximum revenue generated in a single sale. 
select SaleID,max(Revenue) as max_revenue 
from sales 
group by SaleID
order by max_revenue desc limit 1;

-- 16 Identify the minimum revenue generated in a single sale. 
select SaleID,min(Revenue) as min_revenue from sales 
group by SaleID 
order by min_revenue limit 1;

-- 17. Calculate the total quantity sold by each customer. 
select CustomerName, sum(Quantity) as Total_quantity 
from sales s 
join customers c 
on c. CustomerID = s.CustomerID 
group by CustomerName 
order by Total_quantity;

-- 18. Find the total revenue generated by each customer. 

select CustomerName, sum(Revenue) as Total_revenue
from sales s 
join customers c 
on c. CustomerID = s.CustomerID 
group by CustomerName 
order by Total_revenue;

-- 19. Count the number of sales made by customers in the East region. 
select Region ,sum(s.quantity) as Total_sale from sales s 
join customers c 
on c. CustomerID = s.CustomerID
group by Region
 having Region = "East";

-- 20. Retrieve the total quantity sold for Desk Chair. 
select ProductName ,sum(quantity) as Total_sale from sales s 
join products p
on s. ProductID = p.ProductID  
where ProductName="Desk Chair";

select ProductName ,sum(quantity) as Total_sale from sales s 
join products p
on s. ProductID = p.ProductID  
group by ProductName
having ProductName="Desk Chair"