-- 1.Retrieve all sales details along with the corresponding customer names. 
select CustomerName,s. * from sales s
join customers c 
on c. CustomerID = s. CustomerID; 

-- 2.  Retrieve all sales details along with the product names and categories. 
select ProductName,Category ,s. * from sales s 
join products p 
on p.ProductID = s.ProductID; 

-- 3.  List all customers who have made a purchase. 
select distinct (CustomerName) from customers c 
join sales s 
on s.CustomerID = c.CustomerID ;
 
 -- 4.  Find the names of products purchased by Alice Johnson. 
 select p. ProductName, c.CustomerName from customers c  
 join sales s 
 on c.CustomerID =s.CustomerID
 join products p 
 on p.ProductID = s.ProductID 
 where CustomerName = "Alice Johnson";
 
 -- 5. Retrieve the total revenue generated by each customer along with their region.  
 select CustomerName,Region,sum(Revenue) as Total_revenue from customers c
 join sales s 
 on s .CustomerID =c.CustomerID 
 group by CustomerName,Region 
 order by Total_revenue;
 
-- 6. List all products that have been sold, along with their categories. 
select ProductName ,Category,sum(Quantity) as total_sold from 
sales s 
join products p 
on p.ProductID = s.ProductID 
group by ProductName,Category 
order by total_sold; 

-- 7. Show the sales details for customers in the South region. 

select CustomerName ,Region ,s.* from sales s 
join customers c 
on s.CustomerID =c. CustomerID 
where Region ="South";

-- 8. Find the total quantity of each product sold in the North region.
select sum(s.Quantity) as Total_quantity,p.ProductName ,c.Region from sales s
join customers c
on s. CustomerID= C.CustomerID 
join products p 
on p.ProductID = s.ProductID 
group by p.ProductName, c.Region 
having Region = "North";
  
  -- 9. . Retrieve sales details where the product category is Electronics.  
  select s.*, Category from sales s
  join products p 
  on s.ProductID = p.ProductID 
  where Category = "Electronics";
 
 -- 10.List all customers who have purchased a Notebook. 
 select c. CustomerName, p. ProductName from customers c
 join sales s 
 on s . CustomerID = c.CustomerID 
 join  products p 
 on s.ProductID = p.ProductID 
 where ProductName ="Notebook";